import { Role } from '../types/user';

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  [Role.SUPER_ADMIN]: [
    'users:read',
    'users:write',
    'users:delete',
    'societies:read',
    'societies:write',
    'societies:delete',
    'properties:read',
    'properties:write',
    'properties:delete',
    'dealers:read',
    'dealers:write',
    'dealers:approve',
    'leads:read',
    'leads:write',
    'leads:assign',
    'transactions:read',
    'transactions:write',
    'commissions:read',
    'commissions:settle',
    'grievances:read',
    'grievances:write',
    'grievances:escalate',
    'reports:read',
    'reports:export',
    'admin:full',
  ],
  [Role.RWA_ADMIN]: [
    'societies:read',
    'properties:read',
    'properties:approve',
    'dealers:read',
    'dealers:approve',
    'leads:read',
    'transactions:read',
    'grievances:read',
    'grievances:write',
    'reports:read',
  ],
  [Role.DEALER]: [
    'properties:read',
    'leads:read',
    'leads:write',
    'transactions:read',
    'commissions:read',
    'communication:chat',
    'communication:call',
  ],
  [Role.OWNER]: ['properties:read', 'properties:write', 'leads:read', 'transactions:read'],
  [Role.BUYER_TENANT]: ['properties:read', 'leads:create', 'communication:chat'],
};
